apiVersion: enterprisesearch.k8s.elastic.co/v1
kind: EnterpriseSearch
metadata:
  name: enterprise-search
spec:
  version: 7.16.2
  count: 1
  elasticsearchRef:
    name: elasticsearch
  podTemplate:
    spec:
      containers:
      - name: enterprise-search
        resources:
          requests:
            cpu: 2
            memory: 3Gi
          limits:
            cpu: 2
            memory: 3Gi
        env:
        - name: JAVA_OPTS
          value: -Xms7500m -Xmx7500m