name: K8s Casa - Delete ECK (Elastic)

on:
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  GKE_CLUSTER: casa
  GKE_ZONE: europe-west2
  NAMESPACE: casa

jobs:
  cluster-info:
    name: Casa Cluster information
    runs-on: ubuntu-latest
    environment: production

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        token_format: 'access_token'
        workload_identity_provider: '${{ secrets.WIF_PROVIDER }}'
        service_account: '${{ secrets.WIF_SERVICE_ACCOUNT }}'

    - name: Set up GKE credentials
      uses: google-github-actions/get-gke-credentials@v0
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}

    - name: Delete Elastic
      run: |-
        echo "Uninstalling Elastic Cloud Kubernetes..."
        kubectl delete -f eck/enterprise-search.yaml -n ${{ env.NAMESPACE }} --ignore-not-found=true
        kubectl delete -f eck/kibana.yaml -n ${{ env.NAMESPACE }} --ignore-not-found=true
        kubectl delete -f eck/elastic-search-cluster.yaml -n ${{ env.NAMESPACE }} --ignore-not-found=true
        kubectl delete -f https://download.elastic.co/downloads/eck/1.9.1/operator.yaml --ignore-not-found=true
        kubectl delete -f https://download.elastic.co/downloads/eck/1.9.1/crds.yaml	--ignore-not-found=true
        kubectl get namespaces --no-headers -o custom-columns=:metadata.name | xargs -n1 kubectl delete elastic --all -n
        echo "\nFor more information visit: https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-uninstalling-eck.html"
